### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by deknapp** [deknapp/deknapp.github.io#1]
I was able to find work pages at PNNL for the Treases, but I also found obituaries for some other team members. Should I just say team member (deceased) on the team page, or link to an obituary?

@millerta

**Comment by deknapp** [comment]
@cwgable 
Do you know if there is an existing web page relating to Frank Ortega? Something related to gmv perhaps?

**Comment by cwgable** [comment]
http://www.generalmeshviewer.com


=================================================
Dr. Carl W. Gable
Group Leader, Computational Earth Science, EES-16
Earth and Environmental Sciences Division

MS T003, Los Alamos National Laboratory, Los Alamos NM 87545
Email:gable@lanl.gov<mailto:gable@lanl.gov>   Voice:505-665-3533   Cell:505-670-7265
EES-16 Group Office: 667-4266
EES Division Office: 667-3644
Homepage: Carl Gable<http://www.lanl.gov/expertise/profiles/view/carl-gable>
LaGriT<http://lagrit.lanl.gov/> Mesh Generation Software
Discrete Fracture Network: dfnWorks<http://www.lanl.gov/org/padste/adcles/earth-environmental-sciences/computational-earth-science/software/dfnworks/index.php>
Mesh Generation, Geological Applications<http://meshing.lanl.gov/>
Focus:Geophysics, Hydrology, Mesh Generation, Computational Geometry

Schedule B Friday Off
===============Correspondence/TSPA===============

**Comment by deknapp** [comment]
@cwgable I had found that page with a Google search, but I was wondering if there was a page more directly related to Frank Ortega, packed away somewhere within the LANL website.

**Comment by cwgable** [comment]
“Related to Frank…”,  like an obituary? Frank died a number of years ago.

Carl
=================================================
Dr. Carl W. Gable
Group Leader, Computational Earth Science, EES-16
Earth and Environmental Sciences Division

MS T003, Los Alamos National Laboratory, Los Alamos NM 87545
Email:gable@lanl.gov<mailto:gable@lanl.gov>   Voice:505-665-3533   Cell:505-670-7265
EES-16 Group Office: 667-4266
EES Division Office: 667-3644
Homepage: Carl Gable<http://www.lanl.gov/expertise/profiles/view/carl-gable>
LaGriT<http://lagrit.lanl.gov/> Mesh Generation Software
Discrete Fracture Network: dfnWorks<http://www.lanl.gov/org/padste/adcles/earth-environmental-sciences/computational-earth-science/software/dfnworks/index.php>
Mesh Generation, Geological Applications<http://meshing.lanl.gov/>
Focus:Geophysics, Hydrology, Mesh Generation, Computational Geometry

Schedule B Friday Off
===============Correspondence/TSPA===============

**Comment by deknapp** [comment]
This is not an issue anymore. We can talk about whether we want to link to an obituary on Monday. I will close it.
