### ISSUE TITLE
Incorrect input file in crebrickdes1.html

### ISSUE THREAD

**Issue by deknapp** [deknapp/deknapp.github.io#2]
@daniellivingston @millerta It looks like the LaGriT script in credbrickdes1.html is incorrect, so my converted version in markdown (see pages/docs/crebrickdes1.md) is also incorrect. I tried to correct but I don't have a clue what it is doing, could you take a look (it is 10 lines). I don't know the argument structre in quadxyz, but in the original, there are no slashes (see https://github.com/lanl/LaGriT/blob/master/lagrit.lanl.gov/docs/crebrickdes1.html).  Feel free to correct it directly on the repo.

**Comment by millerta** [comment]
This entire page is blech. The description is useless.

Let me take a look at it.

Terry A. Miller
Mesh Generation and Software
Computational Earth Science EES-16
tamiller@lanl.gov<mailto:tamiller@lanl.gov>
505-667-8009




On Sep 7, 2017, at 10:23 AM, deknapp <notifications@github.com<mailto:notifications@github.com>> wrote:


@daniellivingston<https://github.com/daniellivingston> @millerta<https://github.com/millerta> It looks like the LaGriT script in credbrickdes1.html is incorrect, so my converted version in markdown (see pages/docs/crebrickdes1.md) is also incorrect. I tried to correct but I don't have a clue what it is doing, could you take a look (it is 10 lines). I don't know the argument structre in quadxyz, but in the original, there are no slashes (see https://github.com/lanl/LaGriT/blob/master/lagrit.lanl.gov/docs/crebrickdes1.html). Feel free to correct it directly on the repo.

**Comment by daniellivingston** [comment]
Slashes vs. spaces shouldn't be a problem: 

> [Conventions that apply to all commands include:](http://lagrit.lanl.gov/docs/conventions.html)
> 3. Delimiters are comma, slash, equal sign, or blank. (',' '/' '='' ').

The definition for `quadxyz` has an example of the format:

     quadxyz/5 25 7/ 0. 0. 0. /1. 0. 0. /1. .0 10. /0. .0 10. /0. 2.0 0. /1. 2. 0. & 
              /1.0 2. 10.0 /0. 2. 10.0 / 

This is what is in the credbrickdes1 script:

     quadxyz 5 /7 /5 /0. /0. /0. /1. /0. /0. /1.5 /.5 /2. /.5 /.2 /2.5 /-1. /1.5 /0. /2. /2. /0.
     2.1 /1.9 /2.4 /-.2 /1.8 /2.3

Broken script because it's missing an ampersand for the line continuation.

Fixed and edited syntax

**Comment by deknapp** [comment]
Thanks @daniellivingston .
